"use client";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { SeoCounters } from "@/components/SeoCounters";
import { motion } from "framer-motion";
import { Globe, Wrench, Link as LinkIcon, ShoppingBag, MapPin, ArrowRight } from "lucide-react";

const fullSeoFeatures = [
  {
    icon: Globe,
    title: "ON-PAGE OPTIMISATION",
    desc: "The content on your website pages must match the intent and expectations of users so Google ranks your page high in the search. We'll create unique content and make expert optimisations to drive new traffic and clicks.",
  },
  {
    icon: Wrench,
    title: "TECHNICAL SEO",
    desc: "There are hundreds of elements that fall under a technical SEO remit from site speed to re-directs. We'll identify and fix the technical elements of your site to give you a solid SEO foundation for further growth.",
  },
  {
    icon: LinkIcon,
    title: "MEDIA PLACEMENTS & LINKS",
    desc: "High-quality links from reputable sources will increase the trust of your brand in the eyes of Google and your target audience. We'll secure authority-boosting placements to generate impressions, clicks and online sales.",
  },
];

const specializedSeo = [
  {
    icon: ShoppingBag,
    title: "E-Commerce SEO",
    desc: "E-commerce SEO will bring in the right leads who have a direct interest in your brand. Save time and money by targeting a specific niche!",
  },
  {
    icon: MapPin,
    title: "Local SEO",
    desc: "People often look for services around them that are more convenient for them. Even if you provide service globally you can still attract visitors by being available to them on the local search results.",
  },
];

export default function SeoPage() {
  return (
    <>
      <Navbar />
      <main className="pt-32 bg-bg min-h-screen">
        
        {/* Header Section */}
        <div className="max-w-7xl mx-auto px-6 mb-24 text-center">
          <motion.p 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="text-secondary font-bold tracking-widest uppercase mb-4"
          >
            Digital Lab
          </motion.p>
          <motion.h1 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1 }}
            className="text-5xl md:text-7xl font-bold text-navy mb-8 leading-tight"
          >
            Search Engine Optimisation
          </motion.h1>
          <motion.h3 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="text-2xl md:text-3xl text-gray-750 font-light leading-relaxed max-w-4xl mx-auto mb-4"
          >
            Be Found and Visible on Search Engines!
          </motion.h3>
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.3 }}
            className="text-lg text-gray-700 font-light max-w-2xl mx-auto"
          >
            Why do you need SEO, AEO and GEO? Because 92.9% of traffic is generated by Google Search, ChatGPT and other AI engines &mdash; and your brand needs to be visible across all of them.
          </motion.p>
        </div>

        {/* Stats Section (SeoCounters) */}
        <SeoCounters />

        {/* Full-on-Full SEO Section */}
        <div className="py-24 max-w-7xl mx-auto px-6 relative bg-bg">
          <div className="absolute top-0 right-0 w-80 h-80 bg-primary/20 rounded-none blur-[100px] opacity-50 pointer-events-none" />
          
          <div className="text-center mb-16 relative z-10">
            <h2 className="text-4xl md:text-5xl font-bold text-navy mb-6">
              We do full-on SEO for your website
            </h2>
            <p className="text-xl text-gray-500 font-light">Or pick the one you like!</p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-10 relative z-10">
            {fullSeoFeatures.map((item, i) => {
              const Icon = item.icon;
              return (
                <motion.div
                  key={item.title}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  transition={{ delay: i * 0.1 }}
                  className="bg-white p-10 border border-primary/20 hover:border-primary hover:shadow-xl hover:shadow-sky-100/60 transition-all duration-300 group"
                >
                  <div className="w-16 h-16 bg-white border border-primary/20 flex items-center justify-center text-secondary mb-8 group-hover:bg-bg transition-colors duration-300">
                    <Icon className="w-8 h-8 group-hover:scale-110 transition-transform duration-300" />
                  </div>
                  <h3 className="text-xl font-bold text-navy mb-4 tracking-wide">{item.title}</h3>
                  <p className="text-gray-500 font-light leading-relaxed">
                    {item.desc}
                  </p>
                </motion.div>
              );
            })}
          </div>
        </div>

        {/* Specialized SEO Types Section */}
        <div className="bg-bg border-t border-primary/20 py-24 relative overflow-hidden">
          <div className="absolute top-1/2 left-1/4 w-96 h-96 bg-primary rounded-none blur-[150px] opacity-40 pointer-events-none transform -translate-y-1/2" />
          
          <div className="max-w-7xl mx-auto px-6 relative z-10">
            <div className="mb-16">
              <h2 className="text-4xl md:text-5xl font-bold text-navy mb-6">
                Type of SEO you can pick:
              </h2>
              <div className="w-24 h-1 bg-secondary" />
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-12">
              {specializedSeo.map((item, i) => {
                const Icon = item.icon;
                return (
                  <motion.div
                    key={item.title}
                    initial={{ opacity: 0, x: i % 2 === 0 ? -30 : 30 }}
                    whileInView={{ opacity: 1, x: 0 }}
                    viewport={{ once: true }}
                    className="bg-white border border-primary/20 p-12 hover:shadow-xl hover:shadow-sky-100/60 hover:scale-[1.02] transition-all duration-300 cursor-pointer group"
                  >
                    <div className="flex items-center mb-8">
                      <div className="w-16 h-16 bg-white border border-primary/20 flex items-center justify-center text-secondary shadow-md mr-6">
                        <Icon className="w-8 h-8" />
                      </div>
                      <h3 className="text-3xl font-bold text-navy">{item.title}</h3>
                    </div>
                    <p className="text-gray-650 font-light text-xl leading-relaxed mb-10">
                      {item.desc}
                    </p>
                    <div className="flex items-center text-secondary font-bold tracking-widest uppercase text-sm group-hover:text-primary transition-colors">
                      Learn More <ArrowRight className="w-5 h-5 ml-2 group-hover:translate-x-2 transition-transform" />
                    </div>
                  </motion.div>
                );
              })}
            </div>
          </div>
        </div>

      </main>
      <Footer />
    </>
  );
}
