"use client";

import { motion, useInView } from "framer-motion";
import { useRef, useEffect, useState } from "react";

function AnimatedCounter({ end, suffix, label }: { end: number, suffix: string, label: string }) {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true, margin: "-50px" });
  const [count, setCount] = useState(0);

  useEffect(() => {
    if (isInView) {
      let start = 0;
      const duration = 2000; // 2 seconds
      const incrementTime = 20; // 20ms frame
      const steps = duration / incrementTime;
      const stepValue = end / steps;

      const timer = setInterval(() => {
        start += stepValue;
        if (start >= end) {
          setCount(end);
          clearInterval(timer);
        } else {
          setCount(start);
        }
      }, incrementTime);

      return () => clearInterval(timer);
    }
  }, [isInView, end]);

  // Rounding for decimals if end has decimal part
  const displayCount = end % 1 !== 0 ? count.toFixed(1) : Math.floor(count);

  return (
    <div ref={ref} className="text-center p-12 bg-white rounded-none shadow-xl border border-primary/20 hover:border-primary hover:-translate-y-2 transition-transform duration-300">
      <div className="text-6xl md:text-8xl font-bold bg-clip-text text-transparent bg-gradient-to-br from-primary to-secondary mb-6 tracking-tighter">
        {displayCount}{suffix}
      </div>
      <p className="text-xl text-gray-650 font-light leading-relaxed max-w-xs mx-auto">
        {label}
      </p>
    </div>
  );
}

export function SeoCounters() {
  return (
    <section className="bg-bg py-32 border-b border-primary/20">
      <div className="max-w-7xl mx-auto px-6">
        <div className="text-center mb-24">
          <h2 className="text-4xl md:text-5xl font-bold text-navy mb-6">Why do you need SEO, AEO and GEO?</h2>
          <div className="w-20 h-1 bg-secondary mx-auto" />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
          <AnimatedCounter 
            end={68} 
            suffix="%" 
            label="of online experiences start from a search engine."
          />
          <AnimatedCounter 
            end={53.3} 
            suffix="%" 
            label="of all website traffic comes from organic search."
          />
          <AnimatedCounter 
            end={92.9} 
            suffix="%" 
            label="of traffic is generated by Google Search, ChatGPT and more."
          />
        </div>
      </div>
    </section>
  );
}
